version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: awos_school_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IsaacMD78
      POSTGRES_DB: school_db
    ports:
      - "5435:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - school-net

networks:
  school-net:
    driver: bridge